project:
  type: website
  output-dir: ../

website:
  title: "Thinker Mahmud"
  repo-url: https://github.com/mahmudstat/mahmudstat.github.io/
  bread-crumbs: false
  navbar:
    tools:
      - icon: facebook
        href: https://facebook.com/mahmud.sbi
      - icon: github
        href: https://github.com/mahmudstat
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - href: books.qmd
        text: Books
        icon: book
      - href: /stat-lectures
        text: Teaching
        icon: pen
      - href: research.qmd
        text: Reserach
        icon: binoculars
      - href: career.qmd
        text: Career
        icon: graph-up-arrow
      - href: websites.qmd
        text: Websites
        icon: globe2
      - href: writings.qmd
        text: Writings
        icon: pen-fill
      - href: quotes.qmd
        text: Quotes
        icon: blockquote-right

  sidebar:
    style: "docked"
  page-footer: "Copyright 2025, Abdullah Al Mahmud | Website rendered with Quarto"

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



